// <auto-generated />
namespace StaycationMate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SeedAttractions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeedAttractions));
        
        string IMigrationMetadata.Id
        {
            get { return "202109120835550_SeedAttractions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
